[src]
# source db url, need to be a replica set.
url = "mongodb://localhost/"

[oplog]
# mongodb url to sync oplog from source client.
storage_url = "mongodb://localhost/"

[[sync]]
# target db url, don't need to be a replica set.
dst_url = "mongodb://root:Ricemap123@192.168.10.67/?authSource=admin"
# specify database to sync.
db = "bb"
colls = ["a", "b"]

[[sync]]
# target db url, don't need to be a replica set.
dst_url = "mongodb://root:Ricemap123@192.168.10.67/?authSource=admin"
# specify database to sync.
db = "bb"
colls = ["a", "b"]
