[src]
# source db url, need to be a replica set.
url = "mongodb://rice:Ricemap123@localhost/abc?authSource=admin"

[dst]
# target db url, don't need to be a replica set.
url = "mongodb://rice:Ricemap123@localhost/def?authSource=admin"

[sync]
# specify databases to sync
db = "database"
