[src]
# source db url, need to be a replica set.
url = "mongodb://localhost/abc"

[dst]
# target db url, don't need to be a replica set.
url = "mognodb://localhost/def"

[sync]
# specify databases to sync
dbs = [
    # sync a database, `colls` is options, if not provided, sync all
    # collecitons from the given db.
    { db = "database" }
]

[log]
# log config.
optime_path = "/tmp/tmp_oplog_time.log"   # save oplog time locally.
